mysite/app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from .import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('',views.inicio, name ='index'),
    path('index', views.inicio, name='inicio'),
    path('login', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='inicio'), name='logout'),
    path('registro', views.register_view, name='registro'),
    

    path('tipos_te', views.tipo_te, name="tipos_te") ,
    path('pokedex', views.pokedex, name="pokedex"),
    path('tipos_te/te_boldo', views.te_boldo, name="te_boldo"),
    path('tipos_te/te_jazmin', views.te_jazmin, name="te_jazmin"),
    path('tipos_te/te_margarita', views.te_margarita, name="te_margarita"),
    path('tipos_te/te_pasiflora', views.te_pasiflora, name="te_pasiflora"),


    path('post/', views.listar_post, name='listar'),

    # Ruta para crear una nueva publicación
    path('Post/agregar', views.agregar_post, name='agregar'),

    # Ruta para editar una publicación existente
    path('Post/<int:post_id>/editar', views.editar_post, name='editar'),

    # Ruta para eliminar una publicación existente
    path('Post/<int:post_id>/borrar', views.borrar_post, name='borrar'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from app.urls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),

]

mysite/app/models.py
from django.db import models
from django.contrib.auth.models import User


class Ejemplo(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.nombre
    

class Post(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_Post = models.DateTimeField(auto_now_add=True)
    foto = models.ImageField(upload_to='post_photos/')
    titulo =    models.TextField()
    comentario = models.TextField()

    def __str__(self):
        return f"Post {self.id} - Autor: {self.autor.username}"

mysite/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from .models import Post


from .models import Ejemplo

class EjemploForm(forms.ModelForm):
    class Meta:
        model = Ejemplo
        fields = ('nombre', 'email')



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    rut = forms.CharField(max_length=9)
    # Agrega otros campos adicionales aquí

    class Meta (UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'first_name','rut', 'password1', 'password2')


    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            # Eliminar los mensajes de error de validaciones de contraseña
            for field_name in self.fields:
                field = self.fields.get(field_name)
                if field and field.widget.input_type == 'password':
                    field.widget.attrs.pop('autocomplete', None)
                    field.widget.attrs['placeholder'] = field.label
                    field.widget.attrs['class'] = 'form-control'

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['foto', 'titulo' ,'comentario']

mysite/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm, LoginForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
import sweetify

from .forms import EjemploForm

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Post
from .forms import PostForm




#-------------------------------- redirecciones de paginas --------------------------------

def home_view(request):
    return redirect('inicio')


def inicio(request):
    return render(request, 'app/index.html')

def tipo_te(request):
    return render(request, 'app/tes_ext.html')

def pokedex(request):
    return render(request, 'app/pokedex_ext.html')

def te_boldo(request):
    return render(request, 'app/te_boldo.html')

def te_jazmin(request):
    return render (request,'app/te_jazmin.html')

def te_margarita(request):
    return render (request,'app/te_margarita.html')

def te_pasiflora(request):
    return render (request,'app/te_pasiflora.html')


#-------------------------------- ejemplo de form--------------------------------
# def ejemplo_view(request):
#     if request.method == 'POST':
#         form = EjemploForm(request.POST)
#         if form.is_valid():
#             form.save()
#     else:
#         form = EjemploForm()
#     return render(request, 'app/inicio.html', {'form': form})



#-------------------------------- Registrarse --------------------------------
def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  
    else:
        form = RegistrationForm()
    return render(request, 'app/registro.html', {'form': form})


#-------------------------------- Login --------------------------------
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('inicio') 
            else:
                error_message = 'Credenciales inválidas'
    else:
        form = LoginForm()
        error_message = None
    return render(request, 'app/login.html', {'form': form, 'error_message': error_message})

#-------------------------------- logout --------------------------------
def logout_view(request):
    logout(request)
    return redirect('inicio')


#-------------------------------- Sweet alert --------------------------------


def my_view(request):
    sweetify.warning(request, 'This is a warning... I guess')

#-------------------------------- Post --------------------------------

def listar_post(request):
    posts = Post.objects.all()
    return render(request, "post/postListar.html", {'posts': posts})



#agregar crud
@login_required
def agregar_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.autor = request.user
            post.save()
            messages.success(request, '¡Su post ha sido creado!')
            return redirect('listar')
        else:
            messages.error(request, 'Error, no se pudo subir su post')
    else:
        form = PostForm()
    return render(request, 'post/postAgregar.html', {'form': form})






#Borra crud


def borrar_post(request, post_id):
    instancia = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        instancia.delete()  
        return redirect('listar')
    return render(request, 'post/postBorrar.html', {'post': instancia})  







#editar crud

def editar_post(request, post_id):
    instancia = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=instancia)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Post editado correctamente!')
            return redirect('listar')
        else:
            messages.error(request, "Error, No se pudo editar su post")
    else:
        form = PostForm(instance=instancia)
    return render(request, "post/postEditar.html", {'form': form})



mysite/templates/app/index.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load sweetify %}
{% load static %}


{% block css %}
  
{% endblock %}

{% block content %}
<style> 
.carrosel{
  width: 700px;
    right: 50px;
}

.padfotos{
    padding-left: 150px;
    padding-right: 140px;
    padding-bottom: 100px;
    padding-top: 100px;
}


</style>

<div class="container-sm">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carous el">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
          aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
          aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
          aria-label="Slide 3"></button>
      </div>


      <div class="carousel-inner">
        <!-- Esta clase conforma todo lo que esta dentro del carrusel  -->

        <!--carousel item son cada una de las slide del carrusel  imagen 1-->
        <div class="carousel-item active">
          <img src="{% static 'img/guisanteDeMariposa.png' %}" width="400" height="800" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Guisante de Mariposa</h5>
            <p class="txt_carousel">Gracias a su alto contenido de antocianinas, puede mejorar la salud del corazón y el cerebro y
              proporcionar propiedades antidiabéticas, anticancerígenas y antimicrobianas</p>
          </div>
        </div>

        <!-- imagen 2 -->
        <div class="carousel-item">
          <img src="{% static 'img/hibisco.png' %}" width="400" height="800" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Té Hibisco</h5>
            <p class="txt_carousel">Es una planta estomacal y combate la acidez. Además, para cualquier tipo de afección gastrointestinal es
              realmente una maravilla. Favorece a la estimulación de funciones hepáticas, como un
              descongestionante,Ayuda a mantener a raya los niveles de colesterol.</p>
          </div>
        </div>

        <!-- imagen 3 -->
        <div class="carousel-item">
          <img src="{% static 'img/melisa.png' %}" width="400" height="800" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Té Melisa</h5>
            <p class="txt_carousel">posee propiedades antiespasmódicas, favorece el sueño, alivia los dolores de estómago, facilita la
              digestión, calma las náuseas en embarazadas y actúa favorablemente en caso de estrés. También resulta
              agradable por su delicado sabor a limón en refrescos.</p>
          </div>
        </div>
      </div>

      <!-- Esto es para los botones de avanzar o retroceder en el carrusel -->
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>

      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
      <br>

    </div>
  </div>

{% endblock %}

mysite/templates/app/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}



<br><br><br>
<div class="container">
  <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
          <div class="card">
              <div class="card-body bg-white">
                  <h2 class="text-dark text text-center">Ingresa tus Credenciales</h2>
                  <hr class="text-dark">
                  <form action="" method="post">
                      {% csrf_token %}
                      {{form | crispy}}
                      <br>
                      <a href="{% url 'inicio' %}">Ir al inicio</a> |
                      <a href="{% url 'registro' %}">Registrate</a>
                      <input type="submit" value="Ingresar" class="btn btn-success float-end">
                  </form>
              </div>
          </div>
      </div>
  </div>


{% endblock %}

mysite/templates/app/pokedex_ext.html
{% extends 'base.html' %}


{% load static %}

<!-- css -->
{% block css %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="{% static 'css/pokedex.css'%}">

{% endblock %}
<!-- js -->



{% block content %}

  <!-- form -->
  <div class="container">
    <form id="form" method="POST" >
      {% csrf_token %}
        <div class="form-group">
            <label for="pokemon" >Nombre o numero del pokemon</label>
            <input type="text" name="pokemon" id="pokemon" class="form-control required" placeholder="Nombre o numero del pokemon...">                    
        </div>
       
        <br>
        <button class="btn btn-outline-primary" id="submit-form">Cargar Información</button>
    </form>


</div>
  <br>
<!-- en este div esta la carta de pokemon -->
  <div id="info" class="text-center">
    <div class="card">
      <div class="card-header" id="nombreId">
        <p class="card-title" id="nombrePokemon"></p>
        <p class="card-subtitle" id="idPokemon"> </p>
      </div>
      <div class="card-body">
        <div id="imgPokemon">
          </div>
        <div class="pokemon-info">
          <ul>
            <li><strong>Altura:</strong> <span id="alturaPokemon"></span></li>
            <li><strong>Peso:</strong> <span id="pesoPokemon"></span></li>
            <li ><strong>Tipo:</strong><span id="tipoPokemon"></span></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'js/cargaPoke.js' %}"></script>
  
  
<!-- este es un comentariooooo -->
{% endblock %}


mysite/templates/app/registro.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block js%}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}



{% block content %}


<div class="container">
  <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
          <div class="card">
              <div class="card-body bg-white">
                  <h2 class="text-dark text text-center">Ingresa tus Credenciales</h2>
                  <hr class="text-dark">
                  <form action="" method="post" id="formRegistro">
                      {% csrf_token %}
                      {{form | crispy}}
                      <br>
                      <a href="{% url 'inicio' %}">Ir al inicio</a> 
                      <input type="submit" value="Registrar" class="btn btn-success float-end" id="btn_registrar" >
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>

<script src=""></script>

{% endblock %}

mysite/templates/app/te_boldo.html
{% extends 'base.html' %}
{% load static %}

<!-- css -->
{% block css %}
 <link rel="stylesheet" href="{% static 'css/style.css' %}">


{% endblock %}
<!-- js -->

{% block content %}
<style>
  body {
    display: flex;
    flex-direction: column;
    align-items: stretch;
    justify-content: stretch;
    height: 100vh;
    margin: 0;
  }

  .container {
    flex: 1;
    display: flex;
    flex-wrap: wrap;
    align-items: stretch;
    justify-content: stretch;
  }

  .container > div {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 20px;
  }

  .image {
    background-color: lightgray;
  }

  .paragraph {
    background-color: gray;
    color: white;
  }

  .video {
    background-color: darkgray;
  }

  img {
    max-width: 100%;
    height: auto;
  }
</style>
</head>
<body>
<div class="container">
  <div class="image">
    <img src="ruta-a-tu-imagen.jpg" alt="Foto">
  </div>
  <div class="video">
    <iframe width="100%" height="315" src="https://www.youtube.com/embed/tu-video-id" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  <div class="paragraph">
    <p>
      También se le conoce como ‘boldú cimarrón’ y su nombre científico es Peumus boldus. El árbol de boldo pertenece a la familia de las monimiáceas y crece en áreas silvestres y templadas tanto de Chile como de Argentina regiones andinas y de Perú en la región de la Sierra Sur. Desde hace siglos, se consume el boldo crudo o cocido, se emplean las hojas para hacer infusiones y la corteza para diversas preparaciones. Está compuesto por aceites esenciales cineol, eucaliptol y ascaridiol, taninos y flavonoides.
    </p>
    <p>Entre las principales propiedades del té de boldo, podemos destacar sus cualidades:</p>
    <ul>
      <li>Expectorante.</li>
      <li>Sedante.</li>
      <li>Antinflamatorio y analgésico.</li>
      <li>Antioxidante.</li>
      <li>Diurético y depurativo.</li>
      <li>Hepatoprotector, colagogo y colerético.</li>
      <li>Fungicida.</li>
      <li>Antiséptico.</li>
      <li>Digestivo, relajante intestinal y carminativo.</li>
    </ul>
  </div>
</div>




{% endblock %}



mysite/templates/app/te_jazmin.html
{% extends 'base.html' %}
{% load static %}

<!-- css -->
{% block css %}
<style>
.contenedor {
  display: flex;
  flex-flow: row wrap;
  /*fila respeta ancho*/
  font-weight: bold;
  text-align: center;
}
/* esta notación dice:" A todos los elementos 
dentro del contenedor hacer..." */
.contenedor>* {
  padding: 10px;
  flex: 1 100%;
}
.footer {
  background-color: rgba(87, 180, 211, 0.253);
}
.main {
  text-align: left;
  background-color: rgba(64, 192, 235, 0.288);
}
.aside-1 {
  background-color: rgba(150, 230, 104, 0.397);

}
/* agregamos los media queries  */
/* haremos una media querie para las pantallas
de tamaño mediano */
@media screen and (min-width:700px) {
  /* le diremos que a ambos aside compartan
  una fila */
  .aside {
      flex: 0 1;
  }
}
@media screen and (min-width:800px) {
  .main {
      flex: 3 0px;
  }
  .aside-1 {
      order: 1;
  }
  .main {
      order: 2;
  }

  .footer {
      order: 3;
  }
}

#img_margarita{
  width: 700px;
  border-radius:15px
}
#img_te{
  width: 700px;
  border-radius:15px
}

.videos_tes{
  background-color: rgba(137, 209, 209, 0.233);
  
}
</style>

{% endblock %}

<!-- js -->

{% block js %}

{% endblock %}

{% block content %}
<header class="header">
    <h1>Té de Jazmin</h1>
  </header>
  <aside class="aside aside-1"> <img class="card-img-top" src="{% static 'img/téJasmin.jpg' %}"alt="...">
  </aside>
  <article class="main">
    <div id="txt_jazmin">
      <h3>Propiedades y beneficios del té de jazmin </h3>
      <p>El té de jazmín ganó especial popularidad en China durante la dinastía Ming, cuando los motivos florales
        estaban de moda y cubrían pinturas,
        vajillas y bordados en la sociedad y en la cultura china.
        Aunque el tipo más común de té de jazmín sea el té verde (pues se hace a partir de esta infusión),
        también existen el té blanco de jazmín, el té oolong y el té negro de jazmín</p>
      <br>
      <P>Entre las principales propiedades del té de jazmin, podemos destacar sus cualidades:</P>
      <ul>
        <li>Antinflamatorio y analgésico.</li>
        <li>Antioxidante.</li>
        <li>Antivirales.</li>
        <li>Antibacterianas.</li>
        <li>Calmantes</li>
        <li>Emenagogas.</li>
      </ul>

    </div>
  </article>
  <div class="videos_tes">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/K5VYid_ZTHo" title="YouTube video player"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>

</div>

{% endblock %}

<div class="container-fluid">
  <h1>Nuestros té´s principales</h1>
  <br>


  <div class="row">
    <div class="col-md">
      <div class="card">
        <img class="card-img-top" src="{% static 'img/te-de-pasiflora.jpg' %}" alt="...">
        <div class="card-body">
          <h4 class="card-title">Té de pasiflora</h4>
          <p class="card-text"></p>

        </div>
      </div>
    </div>

    <div class="col-md">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Té de margarita</h4>
          <p class="card-text">Se utiliza en compresas para reducir las inflamaciones y es un excelente
            cicatrizante. </p>
          <a href={% url 'te_margarita'%} class="btn btn-primary">conocer mas</a>
        </div>
        <img class="card-img-bottom" src="{% static 'img/te-margarita-.jpg' %}" alt="...">
      </div>
    </div>
  </div>

  <!--otra fila-->
  <br>


  <div class="row">
    <div class="col-md">
      <div class="card">
        <img class="card-img-top" src="{% static 'img/téJasmin.jpg' %}"alt="...">
        <div class="card-body">
          <h4 class="card-title">Té de Jazmin</h4>
          <p class="card-text">Previene el envejecimiento prematuro de nuestras células y nos ayuda a mantenernos
            saludables y a combatir enfermedades. </p>
          <a href={% url 'te_jazmin'%} class="btn btn-primary">conocer mas </a>
        </div>
      </div>
    </div>


    <br>
  </div>
</div>

mysite/templates/app/te_margarita.html
{% extends 'base.html' %}
{% load static %}

<!-- css -->

{% block css %}
<style>
.contenedor {
  display: flex;
  flex-flow: row wrap;
  /*fila respeta ancho*/
  font-weight: bold;
  text-align: center;
}

/* esta notación dice:" A todos los elementos 
dentro del contenedor hacer..." */
.contenedor>* {
  padding: 10px;
  flex: 1 100%;
}



.footer {
  background-color: rgba(87, 180, 211, 0.253);
}

.main {
  text-align: left;
  background-color: rgba(64, 192, 235, 0.288);
}

.aside-1 {
  background-color: rgba(150, 230, 104, 0.397);

}
/* agregamos los media queries  */
/* haremos una media querie para las pantallas
de tamaño mediano */
@media screen and (min-width:700px) {
  /* le diremos que a ambos aside compartan
  una fila */
  .aside {
      flex: 0 1;
  }
}
@media screen and (min-width:800px) {
  .main {
      flex: 3 0px;
  }
  .aside-1 {
      order: 1;
  }
  .main {
      order: 2;
  }

  .footer {
      order: 3;
  }
}
#img_margarita{
  width: 700px;
  border-radius:15px
}
#img_te{
  width: 700px;
  border-radius:15px
}
.videos_tes{
  background-color: rgba(137, 209, 209, 0.233);
  
}
</style>

{% endblock %}

<!-- js -->

{% block js %}

{% endblock %}

{% block content %}
<header class="header">
    <h1>Té de Margarita</h1>
  </header>
  "{% static 'img/Te-de-boldo.jpg' %}"
  <aside class="aside aside-1"> <img class="card-img-bottom" src="{% static 'img/cup-png.jpg' %}" alt="..."></aside>
  <article class="main">
    <div id="txt_margarita">
      <h3>Propiedades y beneficios del té de margarita </h3>
      <p>Es oriunda del norte de Europa, aunque en España la más común es la perteneciente a la variedad Chysanthemum
        frutescens, que procede de las Islas Canarias. La margarita es una planta muy resistente que florece durante
        gran parte del año, desde la primavera hasta el invierno. Necesita mucha agua
        y la luz del sol, aunque también se adapta a vivir en áreas de sombra. No solo es atractiva y da un carácter
        poético al jardín,
        sino que también permite preparar infusiones y, además, sus hojas son comestibles:
        combinadas con diente de león e hinojo, dan como resultado una ensalada excelente.</p>
      <br>
      <P>Entre las principales propiedades del té de jazmin, podemos destacar sus cualidades:</P>
      <ul>
        <li> antiinflamatorias.</li>
        <li>astringentes leves.</li>
        <li>resfriado común.</li>
        <li>dolencias del tracto digestivo.</li>
        <li>menstruación doloross.</li>
        <li>inflamaciones del tracto urinario.</li>
      </ul>

    </div>
  </article>
  <div class="videos_tes">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/zCowvclViIM" title="YouTube video player"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>


{% endblock %}

mysite/templates/post/postAgregar.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!-- css -->
{% block css %}

  <link rel="stylesheet" href="{% static 'css/pokedex.css' %}">

{% endblock %}
<!-- js -->

{% block js %}

{% endblock %}


<!-- contenido de la pagina -->
{% block content %}

<br><br><br>
<div class="container">
  <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
          <div class="card">
              <div class="card-body bg-white">
                  <h2 class="text-dark text text-center">Rellena los campos</h2>
                  <hr class="text-dark">
                  <form action="" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{form | crispy}}
                      <br>
                      <input type="submit" value="Postear" class="btn btn-success float-end">
                  </form>
              </div>
          </div>
      </div>
  </div>
{% endblock %}



mysite/templates/post/postEditar.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!-- css -->
{% block css %}
<style>
  .center-content {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #52e0c9ab;
    height: 100vh;
    text-align: center;
  }

  form {
    display: grid;
    grid-template-columns: auto;
    grid-gap: 10px;
    align-items: center;
    justify-content: center;
  }

    width: 300px;
    margin-bottom: 20px;

  }

  #foto_label {
    font-weight: bold;
    margin-bottom: 5px;
    justify-self: center;
  }

  #btn_guardar {
    margin-top: 20px;

  }
</style>
{% endblock %}




<!-- contenido de la página -->
{% block content %}
  <div class="row-cols-auto">
    <h1>Editar Publicación</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form | crispy}}
      
      <!-- Mostrar la foto actual -->
      <label for="id_foto" id="foto_label">Foto Actual:</label>
      <img src="{{ form.instance.foto.url }}" alt="Foto Actual" id="foto_post">

      <button type="submit" class="btn btn-primary" id="btn_guardar">Guardar cambios</button>
    </form>
  </div>
{% endblock %}

